import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });
import React from "react";

const NoSSR = (props) => <React.Fragment>{props.Footer}</React.Fragment>;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <NoSSR>
        <Footer />
      </NoSSR>
    </html>
  );
}
